[package]
name = "gfx-tuto"
version = "0.1.0"
authors = ["Aganthor <psyluche@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx = "0.18.2"
gfx_window_glutin = "0.31.0"
glutin = "0.22.1"